//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.RequestedHardware = new HashSet<RequestedHardware>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string DeviceType { get; set; }
        public string DeviceModel { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> Technician { get; set; }
        public Nullable<int> TechnicianComment { get; set; }
        public string ClientPhone { get; set; }
        public string ClientName { get; set; }
    
        public virtual OrderStatuses OrderStatuses { get; set; }
        public virtual TechnicianComments TechnicianComments { get; set; }
        public virtual Technicians Technicians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestedHardware> RequestedHardware { get; set; }
    }
}
