//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedHardware
    {
        public int ID_Order { get; set; }
        public string Hardware { get; set; }
        public decimal Cost { get; set; }
        public int Amount { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
